<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="15.1.10" />
    <PackageReference Include="HotChocolate.AspNetCore.CommandLine" Version="15.1.10" />
    <PackageReference Include="HotChocolate.Types.Analyzers" Version="15.1.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\MyApp.DbMigrator\MyApp.DbMigrator.csproj" />
    <ProjectReference Include="..\MyApp.DbSeeder\MyApp.DbSeeder.csproj" />
    <ProjectReference Include="..\MyApp.Infrastructure\MyApp.Infrastructure.csproj" />
    <ProjectReference Include="..\MyApp.Migrations\MyApp.Migrations.csproj" />
    <ProjectReference Include="..\MyApp.Seeding\MyApp.Seeding.csproj" />
  </ItemGroup>
</Project>
